services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis
      - elasticsearch
      - minio

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    env_file: .env
    ports:
      - "9000:9000"
    command: server /data

volumes:
  postgres_data:
  minio_data:
