version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 --chdir /app wsgi:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - elasticsearch
