services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.security.transport.ssl.enabled: false

      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
  web:
    build: .
    command: ["./wait_for_it.sh", "db:5432", "--", "gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app"]
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - elasticsearch
