"""Add correct email fields

Revision ID: 4efcf5318032
Revises: 71411ad891f5
Create Date: 2025-04-23 16:47:31.812258

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4efcf5318032"
down_revision = "71411ad891f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("preferred_email", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("preferred_email")

    # ### end Alembic commands ###
