"""Add onboarding fields to User model

Revision ID: 71411ad891f5
Revises: d36f86000914
Create Date: 2025-04-23 16:18:08.801553

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "71411ad891f5"
down_revision = "d36f86000914"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("first_name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("last_name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("phone_number", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("address", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("leetcode_enabled", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("behavioural_enabled", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(sa.Column("jobs_enabled", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("system_design_enabled", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(sa.Column("resume_url", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("cover_letter_url", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("transcript_url", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("latex_url", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("preferred_job_titles", sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("preferred_companies", sa.String(), nullable=True)
        )
        batch_op.add_column(sa.Column("auto_apply", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("additional_notes", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("onboarding_step", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("onboarding_step")
        batch_op.drop_column("additional_notes")
        batch_op.drop_column("auto_apply")
        batch_op.drop_column("preferred_companies")
        batch_op.drop_column("preferred_job_titles")
        batch_op.drop_column("latex_url")
        batch_op.drop_column("transcript_url")
        batch_op.drop_column("cover_letter_url")
        batch_op.drop_column("resume_url")
        batch_op.drop_column("system_design_enabled")
        batch_op.drop_column("jobs_enabled")
        batch_op.drop_column("behavioural_enabled")
        batch_op.drop_column("leetcode_enabled")
        batch_op.drop_column("address")
        batch_op.drop_column("phone_number")
        batch_op.drop_column("last_name")
        batch_op.drop_column("first_name")

    # ### end Alembic commands ###
