"""Add profile_pic_url to users

Revision ID: 72e3f83c6a2e
Revises: b1dfe3f57983
Create Date: 2025-05-01 18:30:03.763702

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "72e3f83c6a2e"
down_revision = "b1dfe3f57983"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("role_type")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("profile_pic_url", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("profile_pic_url")

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "role_type",
                postgresql.ENUM("intern", "newgrad", name="roletype"),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
