"""Initial migration

Revision ID: a0ab748e70cf
Revises:
Create Date: 2025-04-15 03:09:22.874971

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a0ab748e70cf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("blacklisted", sa.Boolean(), nullable=True),
        sa.Column("follower_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.create_index("idx_company_blacklisted", ["blacklisted"], unique=False)
        batch_op.create_index("idx_company_name", ["name"], unique=False)

    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index("idx_tag_name", ["name"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "role_type", sa.Enum("intern", "newgrad", name="roletype"), nullable=False
        ),
        sa.Column(
            "posted_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "nothing_done",
                "applying",
                "applied",
                "oa",
                "interview",
                "offer",
                "rejected",
                name="status",
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Boolean(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("ats_score", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("idx_job_archived", ["archived"], unique=False)
        batch_op.create_index("idx_job_company_id", ["company_id"], unique=False)
        batch_op.create_index("idx_job_created_at", ["created_at"], unique=False)
        batch_op.create_index("idx_job_deleted", ["deleted"], unique=False)
        batch_op.create_index("idx_job_posted_date", ["posted_date"], unique=False)
        batch_op.create_index("idx_job_priority", ["priority"], unique=False)
        batch_op.create_index("idx_job_role_type", ["role_type"], unique=False)
        batch_op.create_index("idx_job_status", ["status"], unique=False)

    op.create_table(
        "job_attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("object_key", sa.String(), nullable=False),
        sa.Column("attachment_type", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_attachments", schema=None) as batch_op:
        batch_op.create_index("idx_attachment_job_id", ["job_id"], unique=False)
        batch_op.create_index("idx_attachment_type", ["attachment_type"], unique=False)

    op.create_table(
        "job_tags",
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("job_id", "tag_id"),
    )
    with op.batch_alter_table("job_tags", schema=None) as batch_op:
        batch_op.create_index("idx_job_tags_job_id", ["job_id"], unique=False)
        batch_op.create_index("idx_job_tags_tag_id", ["tag_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_tags", schema=None) as batch_op:
        batch_op.drop_index("idx_job_tags_tag_id")
        batch_op.drop_index("idx_job_tags_job_id")

    op.drop_table("job_tags")
    with op.batch_alter_table("job_attachments", schema=None) as batch_op:
        batch_op.drop_index("idx_attachment_type")
        batch_op.drop_index("idx_attachment_job_id")

    op.drop_table("job_attachments")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("idx_job_status")
        batch_op.drop_index("idx_job_role_type")
        batch_op.drop_index("idx_job_priority")
        batch_op.drop_index("idx_job_posted_date")
        batch_op.drop_index("idx_job_deleted")
        batch_op.drop_index("idx_job_created_at")
        batch_op.drop_index("idx_job_company_id")
        batch_op.drop_index("idx_job_archived")

    op.drop_table("jobs")
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index("idx_tag_name")

    op.drop_table("tags")
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.drop_index("idx_company_name")
        batch_op.drop_index("idx_company_blacklisted")

    op.drop_table("companies")
    # ### end Alembic commands ###
