"""empty message

Revision ID: a5c9947ef732
Revises: b1c2d3e4f5a6
Create Date: 2025-04-25 03:10:52.566317

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a5c9947ef732"
down_revision = "b1c2d3e4f5a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_blacklisted_companies",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "company_id"),
    )
    op.create_table(
        "user_whitelisted_companies",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "company_id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("leetcode_goal", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("behavioural_goal", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("jobs_goal", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("system_design_goal", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("system_design_goal")
        batch_op.drop_column("jobs_goal")
        batch_op.drop_column("behavioural_goal")
        batch_op.drop_column("leetcode_goal")

    op.drop_table("user_whitelisted_companies")
    op.drop_table("user_blacklisted_companies")
    # ### end Alembic commands ###
