"""add users table

Revision ID: d36f86000914
Revises: add_company_image_url
Create Date: 2025-04-23 04:20:43.482516

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d36f86000914"
down_revision = "add_company_image_url"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("is_onboarded", sa.Boolean(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("idx_job_archived")
        batch_op.drop_index("idx_job_company_id")
        batch_op.drop_index("idx_job_created_at")
        batch_op.drop_index("idx_job_deleted")
        batch_op.drop_index("idx_job_posted_date")
        batch_op.drop_index("idx_job_priority")
        batch_op.drop_index("idx_job_role_type")
        batch_op.drop_index("idx_job_status")
        batch_op.create_index(
            batch_op.f("ix_jobs_archived"), ["archived"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_jobs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_jobs_deleted"), ["deleted"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_link"), ["link"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_jobs_priority"), ["priority"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_priority"))
        batch_op.drop_index(batch_op.f("ix_jobs_link"))
        batch_op.drop_index(batch_op.f("ix_jobs_deleted"))
        batch_op.drop_index(batch_op.f("ix_jobs_created_at"))
        batch_op.drop_index(batch_op.f("ix_jobs_archived"))
        batch_op.create_index("idx_job_status", ["status"], unique=False)
        batch_op.create_index("idx_job_role_type", ["role_type"], unique=False)
        batch_op.create_index("idx_job_priority", ["priority"], unique=False)
        batch_op.create_index("idx_job_posted_date", ["posted_date"], unique=False)
        batch_op.create_index("idx_job_deleted", ["deleted"], unique=False)
        batch_op.create_index("idx_job_created_at", ["created_at"], unique=False)
        batch_op.create_index("idx_job_company_id", ["company_id"], unique=False)
        batch_op.create_index("idx_job_archived", ["archived"], unique=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
